package com.iTree.entity;

// Generated 2015-10-14 15:24:19 by Hibernate Tools 3.4.0.CR1

/**
 * TMenu generated by hbm2java
 */
public class TMenu implements java.io.Serializable {

	private Integer id;
	private int pid;
	private String menuName;
	private String menuUrl;
	private int menuStatus;

	public TMenu() {
	}

	public TMenu(int pid, String menuName, String menuUrl, int menuStatus) {
		this.pid = pid;
		this.menuName = menuName;
		this.menuUrl = menuUrl;
		this.menuStatus = menuStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	public int getMenuStatus() {
		return this.menuStatus;
	}

	public void setMenuStatus(int menuStatus) {
		this.menuStatus = menuStatus;
	}

}
