package com.iTree.entity;

// Generated 2015-10-14 15:24:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TMessage generated by hbm2java
 */
public class TMessage implements java.io.Serializable {

	private Integer id;
	private String messageContent;
	private Date messageDate;
	private String messageName;
	private String messageTel;
	private int messageStatus;

	public TMessage() {
	}

	public TMessage(String messageContent, Date messageDate, int messageStatus) {
		this.messageContent = messageContent;
		this.messageDate = messageDate;
		this.messageStatus = messageStatus;
	}

	public TMessage(String messageContent, Date messageDate,
			String messageName, String messageTel, int messageStatus) {
		this.messageContent = messageContent;
		this.messageDate = messageDate;
		this.messageName = messageName;
		this.messageTel = messageTel;
		this.messageStatus = messageStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMessageContent() {
		return this.messageContent;
	}

	public void setMessageContent(String messageContent) {
		this.messageContent = messageContent;
	}

	public Date getMessageDate() {
		return this.messageDate;
	}

	public void setMessageDate(Date messageDate) {
		this.messageDate = messageDate;
	}

	public String getMessageName() {
		return this.messageName;
	}

	public void setMessageName(String messageName) {
		this.messageName = messageName;
	}

	public String getMessageTel() {
		return this.messageTel;
	}

	public void setMessageTel(String messageTel) {
		this.messageTel = messageTel;
	}

	public int getMessageStatus() {
		return this.messageStatus;
	}

	public void setMessageStatus(int messageStatus) {
		this.messageStatus = messageStatus;
	}

}
