package com.itree.entity;
// Generated 2015-10-14 15:25:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TNews generated by hbm2java
 */
public class TNews implements java.io.Serializable {

	private Integer id;
	private TPhoto TPhoto;
	private String newsTittle;
	private String newsContent;
	private String newsProfile;
	private String newsAuthor;
	private Date newsDate;
	private int newsStatus;

	public TNews() {
	}

	public TNews(String newsTittle, String newsContent, String newsProfile,
			String newsAuthor, Date newsDate, int newsStatus) {
		this.newsTittle = newsTittle;
		this.newsContent = newsContent;
		this.newsProfile = newsProfile;
		this.newsAuthor = newsAuthor;
		this.newsDate = newsDate;
		this.newsStatus = newsStatus;
	}

	public TNews(TPhoto TPhoto, String newsTittle, String newsContent,
			String newsProfile, String newsAuthor, Date newsDate, int newsStatus) {
		this.TPhoto = TPhoto;
		this.newsTittle = newsTittle;
		this.newsContent = newsContent;
		this.newsProfile = newsProfile;
		this.newsAuthor = newsAuthor;
		this.newsDate = newsDate;
		this.newsStatus = newsStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TPhoto getTPhoto() {
		return this.TPhoto;
	}

	public void setTPhoto(TPhoto TPhoto) {
		this.TPhoto = TPhoto;
	}

	public String getNewsTittle() {
		return this.newsTittle;
	}

	public void setNewsTittle(String newsTittle) {
		this.newsTittle = newsTittle;
	}

	public String getNewsContent() {
		return this.newsContent;
	}

	public void setNewsContent(String newsContent) {
		this.newsContent = newsContent;
	}

	public String getNewsProfile() {
		return this.newsProfile;
	}

	public void setNewsProfile(String newsProfile) {
		this.newsProfile = newsProfile;
	}

	public String getNewsAuthor() {
		return this.newsAuthor;
	}

	public void setNewsAuthor(String newsAuthor) {
		this.newsAuthor = newsAuthor;
	}

	public Date getNewsDate() {
		return this.newsDate;
	}

	public void setNewsDate(Date newsDate) {
		this.newsDate = newsDate;
	}

	public int getNewsStatus() {
		return this.newsStatus;
	}

	public void setNewsStatus(int newsStatus) {
		this.newsStatus = newsStatus;
	}

}
