package com.itree.entity;

// Generated 2015-10-14 15:25:59 by Hibernate Tools 3.4.0.CR1

/**
 * TTeacherwrote generated by hbm2java
 */
public class TTeacherwrote implements java.io.Serializable {

	private Integer id;
	private TUser TUser;
	private String teacherContent;
	private int contentStatus;

	public TTeacherwrote() {
	}

	public TTeacherwrote(TUser TUser, String teacherContent, int contentStatus) {
		this.TUser = TUser;
		this.teacherContent = teacherContent;
		this.contentStatus = contentStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public String getTeacherContent() {
		return this.teacherContent;
	}

	public void setTeacherContent(String teacherContent) {
		this.teacherContent = teacherContent;
	}

	public int getContentStatus() {
		return this.contentStatus;
	}

	public void setContentStatus(int contentStatus) {
		this.contentStatus = contentStatus;
	}

}
