package com.iTree.iTreewebCMS.model;

// Generated 2015-10-14 15:19:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TDuty generated by hbm2java
 */
public class TDuty implements java.io.Serializable {

	private Integer id;
	private String dutyName;
	private int dutyStatus;
	private Set TUsers = new HashSet(0);

	public TDuty() {
	}

	public TDuty(String dutyName, int dutyStatus) {
		this.dutyName = dutyName;
		this.dutyStatus = dutyStatus;
	}

	public TDuty(String dutyName, int dutyStatus, Set TUsers) {
		this.dutyName = dutyName;
		this.dutyStatus = dutyStatus;
		this.TUsers = TUsers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDutyName() {
		return this.dutyName;
	}

	public void setDutyName(String dutyName) {
		this.dutyName = dutyName;
	}

	public int getDutyStatus() {
		return this.dutyStatus;
	}

	public void setDutyStatus(int dutyStatus) {
		this.dutyStatus = dutyStatus;
	}

	public Set getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set TUsers) {
		this.TUsers = TUsers;
	}

}
